source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-remote-theme", "~> 0.4.3"
gem "jekyll-paginate"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "webrick"
gem "erb"
gem "logger"
gem "liquid", "~> 4.0.4"
